baseURL: ""
languageCode: en-us
title: Bart Cocquyt
theme: PaperMod

params:
  homeInfoParams:
    Title: "Welcome"
    Content: Welcome to my Site. here you find interesting information on a variaty of tech topics.'
  socialIcons:
    - name: facebook
      url: "https://facebook.com"
    - name: linkedin
      url: "https://linkedin.com/in/bart-cocquyt"
    - name: github
      url: "https://github.com/scan-dev"

  cover:
    linkFullImages: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true

menu: 
  main:
    - identifier: about
      name About
    - identifier: categories
      name: Categories
      url: /categories
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives
      weight: 30